import express from 'express';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import archiver from 'archiver';
import { v4 as uuidv4 } from 'uuid';
import { authMiddleware } from '../middleware/auth.js';
import { findById, updateOne } from '../utils/db.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DEPLOYED_DIR = path.join(__dirname, '../../storage/deployed');

const router = express.Router();

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

router.post('/', authMiddleware, async (req, res) => {
  try {
    const { projectId } = req.body;
    if (!projectId) return res.status(400).json({ error: 'Project ID required' });

    const project = await findById('projects', projectId);
    if (!project) return res.status(404).json({ error: 'Project not found' });
    if (project.userId !== req.user.id) return res.status(403).json({ error: 'Access denied' });

    const user = await findById('users', req.user.id);
    if (user.plan === 'free') {
      return res.status(403).json({
        error: 'Deploy requires Pro or Studio plan',
        upgradeRequired: true
      });
    }

    const deployId = project.id;
    const deployDir = path.join(DEPLOYED_DIR, deployId);
    await ensureDir(deployDir);

    let htmlContent;
    if (project.language === 'html' || project.code.trimStart().startsWith('<!DOCTYPE') || project.code.trimStart().startsWith('<html')) {
      htmlContent = project.code;
    } else if (project.language === 'javascript' || project.language === 'typescript') {
      htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${project.title}</title>
  <style>
    body { background: #0a0a0f; color: white; font-family: sans-serif; margin: 0; padding: 2rem; }
  </style>
</head>
<body>
  <div id="app"></div>
  <script>
${project.code}
  </script>
</body>
</html>`;
    } else {
      const escapedCode = project.code.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
      htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${project.title}</title>
  <style>
    body { background: #0a0a0f; color: white; font-family: monospace; padding: 2rem; }
    pre { background: #1e1e2e; padding: 1.5rem; border-radius: 0.5rem; overflow: auto; }
  </style>
</head>
<body>
  <h1 style="color: #a855f7;">${project.title}</h1>
  <pre><code>${escapedCode}</code></pre>
</body>
</html>`;
    }

    await fs.writeFile(path.join(deployDir, 'index.html'), htmlContent);

    const backendUrl = `http://localhost:${process.env.PORT || 3001}`;
    const deployUrl = `${backendUrl}/deployed/${deployId}/index.html`;

    await updateOne('projects', projectId, { deployUrl, updatedAt: new Date().toISOString() });

    res.json({ success: true, deployUrl, projectId: deployId });
  } catch (err) {
    console.error('Deploy error:', err);
    res.status(500).json({ error: 'Deploy failed: ' + err.message });
  }
});

router.post('/unity/export', authMiddleware, async (req, res) => {
  try {
    const { projectId } = req.body;

    const user = await findById('users', req.user.id);
    if (user.plan === 'free') {
      return res.status(403).json({
        error: 'Unity export requires Pro or Studio plan',
        upgradeRequired: true
      });
    }

    const project = await findById('projects', projectId);
    if (!project) return res.status(404).json({ error: 'Project not found' });
    if (project.userId !== req.user.id) return res.status(403).json({ error: 'Access denied' });

    let code = project.code;

    if (!code.includes('MonoBehaviour') && !code.includes('using UnityEngine')) {
      const className = project.title.replace(/[^a-zA-Z0-9]/g, '') || 'GeneratedScript';
      code = `using UnityEngine;
using System.Collections;
using System.Collections.Generic;

/// <summary>
/// Generated by NovaBuilder AI
/// Prompt: ${project.prompt}
/// </summary>
public class ${className} : MonoBehaviour
{
    void Start()
    {
        // Initialization
    }

    void Update()
    {
        // Called every frame
    }

    /* Original generated code:
${code}
    */
}`;
    }

    const filename = `${project.title.replace(/[^a-zA-Z0-9]/g, '_')}.cs`;

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(code);
  } catch (err) {
    console.error('Unity export error:', err);
    res.status(500).json({ error: 'Export failed' });
  }
});

router.post('/unity/zip', authMiddleware, async (req, res) => {
  try {
    const { projectId } = req.body;

    const user = await findById('users', req.user.id);
    if (user.plan === 'free') {
      return res.status(403).json({
        error: 'Unity export requires Pro or Studio plan',
        upgradeRequired: true
      });
    }

    const project = await findById('projects', projectId);
    if (!project) return res.status(404).json({ error: 'Project not found' });
    if (project.userId !== req.user.id) return res.status(403).json({ error: 'Access denied' });

    let code = project.code;
    if (!code.includes('MonoBehaviour') && !code.includes('using UnityEngine')) {
      const className = project.title.replace(/[^a-zA-Z0-9]/g, '') || 'GeneratedScript';
      code = `using UnityEngine;
using System.Collections;

public class ${className} : MonoBehaviour
{
    void Start() { }
    void Update() { }
}`;
    }

    const scriptName = `${project.title.replace(/[^a-zA-Z0-9]/g, '_')}.cs`;

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${project.title}_UnityProject.zip"`);

    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.pipe(res);
    archive.append(code, { name: `Assets/Scripts/${scriptName}` });
    archive.append('# Unity Project generated by NovaBuilder\n', { name: 'README.md' });

    await archive.finalize();
  } catch (err) {
    console.error('Unity ZIP error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'ZIP export failed' });
    }
  }
});

export default router;
